[package]
name = "atlas-ui-icons"
description = "Icon contracts and assets for Atlas UI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
documentation = "https://docs.rs/atlas-ui-icons/0.1.1"
repository.workspace = true
homepage.workspace = true
readme = false

[dependencies]
atlas-ui-tokens = { path = "../atlas-ui-tokens", version = "=0.1.1" }

[lints]
workspace = true
