[package]
name = "atlas-ui-core"
description = "Visual and interaction primitives for Atlas UI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
documentation = "https://docs.rs/atlas-ui-core/0.2.1"
repository.workspace = true
homepage.workspace = true
readme = false

[dependencies]
atlas-ui-tokens = { path = "../atlas-ui-tokens", version = "=0.2.1" }

[lints]
workspace = true
