[package]
name = "atlas-ui-tokens"
description = "Design tokens and theme contracts for Atlas UI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
documentation = "https://docs.rs/atlas-ui-tokens/0.1.1"
repository.workspace = true
homepage.workspace = true
readme = false

[lints]
workspace = true
