[package]
name = "atlas-ui-gallery"
description = "Native component gallery for Atlas UI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[dependencies]
atlas-ui-components = { path = "../../crates/atlas-ui-components", version = "=0.2.0" }
image.workspace = true
slint.workspace = true

[build-dependencies]
atlas-ui = { path = "../../crates/atlas-ui", version = "=0.2.0" }
slint-build.workspace = true

[lints]
workspace = true
