[package]
name = "atlas-ui-testing"
description = "Test fixtures and validation helpers for Atlas UI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
documentation = "https://docs.rs/atlas-ui-testing/0.2.1"
repository.workspace = true
homepage.workspace = true
readme = false

[dependencies]
image.workspace = true

[lints]
workspace = true
