[package]
name = "atlas-ui-testing"
description = "Test fixtures and validation helpers for Atlas UI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
documentation = "https://docs.rs/atlas-ui-testing/0.2.0"
repository.workspace = true
homepage.workspace = true
readme = false

[dependencies]
atlas-ui-core = { path = "../atlas-ui-core", version = "=0.2.0" }
image.workspace = true
slint.workspace = true

[build-dependencies]
atlas-ui = { path = "../atlas-ui", version = "=0.2.0" }
slint-build.workspace = true

[lints]
workspace = true
